"""update_cascade_delete_relationships

Revision ID: 84816c7fc270
Revises: 474207521aac
Create Date: 2024-12-09 11:09:32.276367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84816c7fc270'
down_revision: Union[str, None] = '474207521aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_ibfk_1', 'channels', type_='foreignkey')
    op.create_foreign_key(None, 'channels', 'users', ['channel_admin_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('company_info_ibfk_1', 'company_info', type_='foreignkey')
    op.create_foreign_key(None, 'company_info', 'users', ['post_initiator_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('report_transactions_ibfk_3', 'report_transactions', type_='foreignkey')
    op.drop_constraint('report_transactions_ibfk_2', 'report_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'report_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'report_transactions', 'company_reports', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_transactions', type_='foreignkey')
    op.drop_constraint(None, 'report_transactions', type_='foreignkey')
    op.create_foreign_key('report_transactions_ibfk_2', 'report_transactions', 'company_reports', ['report_id'], ['id'])
    op.create_foreign_key('report_transactions_ibfk_3', 'report_transactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'company_info', type_='foreignkey')
    op.create_foreign_key('company_info_ibfk_1', 'company_info', 'users', ['post_initiator_user_id'], ['id'])
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.create_foreign_key('channels_ibfk_1', 'channels', 'users', ['channel_admin_id'], ['id'])
    # ### end Alembic commands ###
