"""add_channel_and_report_transaction_models

Revision ID: 8ae517d07485
Revises: fa4dedeccf6e
Create Date: 2024-12-09 00:11:16.695366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae517d07485'
down_revision: Union[str, None] = 'fa4dedeccf6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
