"""remove_companies_relationship_from_user

Revision ID: d4762f1624ac
Revises: add_company_info_fields
Create Date: 2024-12-06 09:18:19.938136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4762f1624ac'
down_revision: Union[str, None] = 'add_company_info_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
