"""Add Channel and ReportTransaction models

Revision ID: fa4dedeccf6e
Revises: d4762f1624ac
Create Date: 2024-12-08 15:55:30.729613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4dedeccf6e'
down_revision: Union[str, None] = 'd4762f1624ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_number', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=225), nullable=False),
    sa.Column('channel_location', sa.String(length=225), nullable=True),
    sa.Column('industry', sa.String(length=225), nullable=True),
    sa.Column('contact_person', sa.String(length=225), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=225), nullable=True),
    sa.Column('registration_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('website', sa.String(length=225), nullable=True),
    sa.Column('app', sa.String(length=225), nullable=True),
    sa.Column('official_account', sa.String(length=225), nullable=True),
    sa.Column('douyin_account', sa.String(length=225), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_number')
    )
    op.create_table('report_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['company_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'channel_id')
    op.drop_table('report_transactions')
    op.drop_table('channels')
    # ### end Alembic commands ###
